<?php
header ("Content-Type:text/xml");
?>
<myXML>
		<filterItem>
        	<mainCat>
            	<mname>Gender</mname>
                <subCat>
                	<name>Male</name>
                    <imagex>0</imagex>
                    <imagey>-70</imagey>
                </subCat>
                <subCat>
                	<name>Female</name>
                    <imagex>0</imagex>
                    <imagey>0</imagey>
                </subCat>
            </mainCat>
         </filterItem>
</myXML>
