<?php

function get_badges($u_id) {
	$output = '';
	
	// get the user's country badge
	$output .= get_country_badge($u_id);
	
	if ($output == '') {
		$output = '{ no badges }';
	}
	echo $output;
}
function get_country_badge($u_id) {
	$c_code = '';
	$result = mysql_query("SELECT country FROM accounts WHERE id='$u_id' LIMIT 1");
	if (mysql_num_rows($result) > 0) {
		$row = mysql_fetch_array($result);
		$c_code = strtoupper($row['country']);
	}
	if ($c_code != '') {
		$c_english = get_country_name($c_code);
		$img = $prefs_sitebase.'/images/icons/flags/'.strtolower($c_code);
		return '<img src="'.$img.'.png" alt="'.$c_english.'" title="'.$c_english.'" />';
	}
	else {
		return '';
	}
}
function get_country_name($code) {
	switch ($code) {
		case 'US': return 'United States'; break;
		case 'AX': return 'Åland Islands'; break;
		case 'AF': return 'Afghanistan'; break;
		case 'AL': return 'Albania'; break;
		case 'DZ': return 'Algeria'; break;
		case 'AS': return 'American Samoa'; break;
		case 'AD': return 'Andorra'; break;
		case 'AO': return 'Angola'; break;
		case 'AI': return 'Anguilla'; break;
		case 'AQ': return 'Antarctica'; break;
		case 'AG': return 'Antigua And Barbuda'; break;
		case 'AR': return 'Argentina'; break;
		case 'AM': return 'Armenia'; break;
		case 'AW': return 'Aruba'; break;
		case 'AU': return 'Australia'; break;
		case 'AT': return 'Austria'; break;
		case 'AZ': return 'Azerbaijan'; break;
		case 'BS': return 'Bahamas'; break;
		case 'BH': return 'Bahrain'; break;
		case 'BD': return 'Bangladesh'; break;
		case 'BB': return 'Barbados'; break;
		case 'BY': return 'Belarus'; break;
		case 'BE': return 'Belgium'; break;
		case 'BZ': return 'Belize'; break;
		case 'BJ': return 'Benin'; break;
		case 'BM': return 'Bermuda'; break;
		case 'BT': return 'Bhutan'; break;
		case 'BO': return 'Bolivia'; break;
		case 'BA': return 'Bosnia And Herzegovina'; break;
		case 'BW': return 'Botswana'; break;
		case 'BV': return 'Bouvet Island'; break;
		case 'BR': return 'Brazil'; break;
		case 'IO': return 'British Indian Ocean Territory'; break;
		case 'BN': return 'Brunei Darussalam'; break;
		case 'BG': return 'Bulgaria'; break;
		case 'BF': return 'Burkina Faso'; break;
		case 'BI': return 'Burundi'; break;
		case 'KH': return 'Cambodia'; break;
		case 'CM': return 'Cameroon'; break;
		case 'CA': return 'Canada'; break;
		case 'CV': return 'Cape Verde'; break;
		case 'KY': return 'Cayman Islands'; break;
		case 'CF': return 'Central African Republic'; break;
		case 'TD': return 'Chad'; break;
		case 'CL': return 'Chile'; break;
		case 'CN': return 'China'; break;
		case 'CX': return 'Christmas Island'; break;
		case 'CC': return 'Cocos (keeling) Islands'; break;
		case 'CO': return 'Colombia'; break;
		case 'KM': return 'Comoros'; break;
		case 'CG': return 'Congo'; break;
		case 'CD': return 'Congo, The Democratic Republic Of The'; break;
		case 'CK': return 'Cook Islands'; break;
		case 'CR': return 'Costa Rica'; break;
		case 'CI': return 'Côte d\'Ivoire'; break;
		case 'HR': return 'Croatia'; break;
		case 'CU': return 'Cuba'; break;
		case 'CY': return 'Cyprus'; break;
		case 'CZ': return 'Czech Republic'; break;
		case 'DK': return 'Denmark'; break;
		case 'DJ': return 'Djibouti'; break;
		case 'DM': return 'Dominica'; break;
		case 'DO': return 'Dominican Republic'; break;
		case 'EC': return 'Ecuador'; break;
		case 'EG': return 'Egypt'; break;
		case 'SV': return 'El Salvador'; break;
		case 'GQ': return 'Equatorial Guinea'; break;
		case 'ER': return 'Eritrea'; break;
		case 'EE': return 'Estonia'; break;
		case 'ET': return 'Ethiopia'; break;
		case 'FK': return 'Falkland Islands (malvinas)'; break;
		case 'FO': return 'Faroe Islands'; break;
		case 'FJ': return 'Fiji'; break;
		case 'FI': return 'Finland'; break;
		case 'FR': return 'France'; break;
		case 'GF': return 'French Guiana'; break;
		case 'PF': return 'French Polynesia'; break;
		case 'TF': return 'French Southern Territories'; break;
		case 'GA': return 'Gabon'; break;
		case 'GM': return 'Gambia'; break;
		case 'GE': return 'Georgia'; break;
		case 'DE': return 'Germany'; break;
		case 'GH': return 'Ghana'; break;
		case 'GI': return 'Gibraltar'; break;
		case 'GR': return 'Greece'; break;
		case 'GL': return 'Greenland'; break;
		case 'GD': return 'Grenada'; break;
		case 'GP': return 'Guadeloupe'; break;
		case 'GU': return 'Guam'; break;
		case 'GT': return 'Guatemala'; break;
		case 'GG': return 'Guernsey'; break;
		case 'GN': return 'Guinea'; break;
		case 'GW': return 'Guinea-bissau'; break;
		case 'GY': return 'Guyana'; break;
		case 'HT': return 'Haiti'; break;
		case 'HM': return 'Heard Island And Mcdonald Islands'; break;
		case 'HN': return 'Honduras'; break;
		case 'HK': return 'Hong Kong'; break;
		case 'HU': return 'Hungary'; break;
		case 'IS': return 'Iceland'; break;
		case 'IN': return 'India'; break;
		case 'ID': return 'Indonesia'; break;
		case 'IR': return 'Iran, Islamic Republic Of'; break;
		case 'IQ': return 'Iraq'; break;
		case 'IE': return 'Ireland'; break;
		case 'IM': return 'Isle Of Man'; break;
		case 'IL': return 'Israel'; break;
		case 'IT': return 'Italy'; break;
		case 'JM': return 'Jamaica'; break;
		case 'JP': return 'Japan'; break;
		case 'JE': return 'Jersey'; break;
		case 'JO': return 'Jordan'; break;
		case 'KZ': return 'Kazakhstan'; break;
		case 'KE': return 'Kenya'; break;
		case 'KI': return 'Kiribati'; break;
		case 'KP': return 'Korea, Democratic People\'s Republic Of'; break;
		case 'KR': return 'Korea, Republic Of'; break;
		case 'KW': return 'Kuwait'; break;
		case 'KG': return 'Kyrgyzstan'; break;
		case 'LA': return 'Lao People\'s Democratic Republic'; break;
		case 'LV': return 'Latvia'; break;
		case 'LB': return 'Lebanon'; break;
		case 'LS': return 'Lesotho'; break;
		case 'LR': return 'Liberia'; break;
		case 'LY': return 'Libyan Arab Jamahiriya'; break;
		case 'LI': return 'Liechtenstein'; break;
		case 'LT': return 'Lithuania'; break;
		case 'LU': return 'Luxembourg'; break;
		case 'MO': return 'Macao'; break;
		case 'MK': return 'Macedonia, The Former Yugoslav Republic Of'; break;
		case 'MG': return 'Madagascar'; break;
		case 'MW': return 'Malawi'; break;
		case 'MY': return 'Malaysia'; break;
		case 'MV': return 'Maldives'; break;
		case 'ML': return 'Mali'; break;
		case 'MT': return 'Malta'; break;
		case 'MH': return 'Marshall Islands'; break;
		case 'MQ': return 'Martinique'; break;
		case 'MR': return 'Mauritania'; break;
		case 'MU': return 'Mauritius'; break;
		case 'YT': return 'Mayotte'; break;
		case 'MX': return 'Mexico'; break;
		case 'FM': return 'Micronesia, Federated States Of'; break;
		case 'MD': return 'Moldova'; break;
		case 'MC': return 'Monaco'; break;
		case 'MN': return 'Mongolia'; break;
		case 'ME': return 'Montenegro'; break;
		case 'MS': return 'Montserrat'; break;
		case 'MA': return 'Morocco'; break;
		case 'MZ': return 'Mozambique'; break;
		case 'MM': return 'Myanmar'; break;
		case 'NA': return 'Namibia'; break;
		case 'NR': return 'Nauru'; break;
		case 'NP': return 'Nepal'; break;
		case 'NL': return 'Netherlands'; break;
		case 'AN': return 'Netherlands Antilles'; break;
		case 'NC': return 'New Caledonia'; break;
		case 'NZ': return 'New Zealand'; break;
		case 'NI': return 'Nicaragua'; break;
		case 'NE': return 'Niger'; break;
		case 'NG': return 'Nigeria'; break;
		case 'NU': return 'Niue'; break;
		case 'NF': return 'Norfolk Island'; break;
		case 'MP': return 'Northern Mariana Islands'; break;
		case 'NO': return 'Norway'; break;
		case 'OM': return 'Oman'; break;
		case 'PK': return 'Pakistan'; break;
		case 'PW': return 'Palau'; break;
		case 'PS': return 'Palestinian Territory, Occupied'; break;
		case 'PA': return 'Panama'; break;
		case 'PG': return 'Papua New Guinea'; break;
		case 'PY': return 'Paraguay'; break;
		case 'PE': return 'Peru'; break;
		case 'PH': return 'Philippines'; break;
		case 'PN': return 'Pitcairn'; break;
		case 'PL': return 'Poland'; break;
		case 'PT': return 'Portugal'; break;
		case 'PR': return 'Puerto Rico'; break;
		case 'QA': return 'Qatar'; break;
		case 'RE': return 'Réunion'; break;
		case 'RO': return 'Romania'; break;
		case 'RU': return 'Russian Federation'; break;
		case 'RW': return 'Rwanda'; break;
		case 'BL': return 'Saint Barthélemy'; break;
		case 'SH': return 'Saint Helena'; break;
		case 'KN': return 'Saint Kitts And Nevis'; break;
		case 'LC': return 'Saint Lucia'; break;
		case 'MF': return 'Saint Martin'; break;
		case 'PM': return 'Saint Pierre And Miquelon'; break;
		case 'VC': return 'Saint Vincent And The Grenadines'; break;
		case 'WS': return 'Samoa'; break;
		case 'SM': return 'San Marino'; break;
		case 'ST': return 'Sao Tome And Principe'; break;
		case 'SA': return 'Saudi Arabia'; break;
		case 'SN': return 'Senegal'; break;
		case 'RS': return 'Serbia'; break;
		case 'SC': return 'Seychelles'; break;
		case 'SL': return 'Sierra Leone'; break;
		case 'SG': return 'Singapore'; break;
		case 'SK': return 'Slovakia'; break;
		case 'SI': return 'Slovenia'; break;
		case 'SB': return 'Solomon Islands'; break;
		case 'SO': return 'Somalia'; break;
		case 'ZA': return 'South Africa'; break;
		case 'GS': return 'South Georgia And The South Sandwich Islands'; break;
		case 'ES': return 'Spain'; break;
		case 'LK': return 'Sri Lanka'; break;
		case 'SD': return 'Sudan'; break;
		case 'SR': return 'Suriname'; break;
		case 'SJ': return 'Svalbard And Jan Mayen'; break;
		case 'SZ': return 'Swaziland'; break;
		case 'SE': return 'Sweden'; break;
		case 'CH': return 'Switzerland'; break;
		case 'SY': return 'Syrian Arab Republic'; break;
		case 'TW': return 'Taiwan, Province Of China'; break;
		case 'TJ': return 'Tajikistan'; break;
		case 'TZ': return 'Tanzania, United Republic Of'; break;
		case 'TH': return 'Thailand'; break;
		case 'TL': return 'Timor-leste'; break;
		case 'TG': return 'Togo'; break;
		case 'TK': return 'Tokelau'; break;
		case 'TO': return 'Tonga'; break;
		case 'TT': return 'Trinidad And Tobago'; break;
		case 'TN': return 'Tunisia'; break;
		case 'TR': return 'Turkey'; break;
		case 'TM': return 'Turkmenistan'; break;
		case 'TC': return 'Turks And Caicos Islands'; break;
		case 'TV': return 'Tuvalu'; break;
		case 'UG': return 'Uganda'; break;
		case 'UA': return 'Ukraine'; break;
		case 'AE': return 'United Arab Emirates'; break;
		case 'GB': return 'United Kingdom'; break;
		case 'UM': return 'United States Minor Outlying Islands'; break;
		case 'UY': return 'Uruguay'; break;
		case 'UZ': return 'Uzbekistan'; break;
		case 'VU': return 'Vanuatu'; break;
		case 'VA': return 'Vatican City State'; break;
		case 'VE': return 'Venezuela'; break;
		case 'VN': return 'Viet Nam'; break;
		case 'VG': return 'Virgin Islands, British'; break;
		case 'VI': return 'Virgin Islands, U.S.'; break;
		case 'WF': return 'Wallis And Futuna'; break;
		case 'EH': return 'Western Sahara'; break;
		case 'YE': return 'Yemen'; break;
		case 'ZM': return 'Zambia'; break;
		case 'ZW': return 'Zimbabwe'; break;
	}
}

?>